version: "2"
linters:
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - goconst
    - gocritic
    - gosec
    - nilnil
    - revive
  exclusions:
    presets:
      - comments
